spring.cloud.azure.servicebus.credential.client-id=xxx
spring.cloud.azure.servicebus.credential.client-secret=xxx
spring.cloud.azure.servicebus.profile.tenant-id=xxx
spring.cloud.azure.servicebus.namespace=xxx
asb.topic.name=fop-demo